FROM indigodatacloudapps/ambertools-oneclient
MAINTAINER Andrea Giachetti <giachetti@cerm.unifi.it>
LABEL description="Container image to run AmberTools v16. Installed Oneclient"

ENV PROVIDER_HOSTNAME=PROVIDER2
ENV ONECLIENT_AUTHORIZATION_TOKEN='TOKEN1'
ENV MOUNT_POINT=/tmp/onedata
ENV WANIP=wanip1
ENV SECHASH=sechash1
RUN mkdir /tmp/onedata
WORKDIR /opt/mds2/
RUN git clone https://github.com/andreagia/MDS2.git
WORKDIR /opt/mds2/MDS2
RUN echo "login.token=$SECHASH" > ./src/main/webapp/resources/application.properties
RUN keytool -genkey -alias jetty -keyalg RSA -keystore ./jetty.keystore -storepass secret -keypass secret -dname "CN=$WANIP"
CMD oneclient --no_check_certificate --authentication  token $MOUNT_POINT; mvn jetty:run
